theme: jekyll-theme-minimal
title: Manikanta's page
description: I'm a software engineer with over a decade of hands-on experience in research and development initiatives across diverse sectors, including Financial Services, International Remittance Services, and Supply Chain Domains. 
baseurl: ""
url: "https://manichalla.com"
#theme: jekyll-theme-slate  # Classic default theme
markdown: kramdown

navigation:
  - title: Home
    url: /
  - title: Lifestyle
    url: /lifestyle/
  - title: Tech & Solutions
    url: /tech/
  - title: Experiences
    url: /experiences/
  - title: About Me
    url: /aboutme/